name: Version Bump

on:
  push:
    branches:
      - main
      - develop

jobs:
  version-bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          
      - name: Version Bump
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            npm version minor -m "bump version to %s [skip ci]"
          else
            npm version patch -m "bump version to %s [skip ci]"
          fi
          
      - name: Push changes
        run: git push --follow-tags 